### ISSUE TITLE
ESP32 C3 compatibility

### ISSUE THREAD

**Issue by joostbijl** [mmakaay/esphome-smartmeter#3]
Hi,

Thanks for this nice project!

i've installed a Wemos C3 Mini on top of the pcb. This compiles and seems to work somewhat with the config below. I can connect it to home assistant, but i don't see any values, only ' unknown'. 

D1 dsmr alias d5 = gpio 14  >> gpio1 on C3
D1 uart alias d7 = gpio 13  >> gpio4 on C3

Everything loks good, but no data :). Is there something obvious i might be missing? Or is there a way to validate esphome receives the data correctly from the P1 port?

```
substitutions:
  name: dsmr-reader
  friendly_name: DSMR Reader

esphome:
  name: ts27meter
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0

logger:
  # Serial logging is disabled by setting the logger baud rate to 0.
  # Otherwise the logger will occupy the hardware UART, making it unavailable
  # for receiving smart meter data on pin D7 (GPIO13).
  baud_rate: 0
  level: VERBOSE

# Enable Home Assistant API
api:
  password: "xx"

ota:
  password: ""

wifi:
  ssid: "xx"
  password: "xx"
  output_power: "8.5"

uart:
  rx_pin: GPIO4
  baud_rate: 115200
  rx_buffer_size: 1500

dsmr:
  request_pin: GPIO1
  request_interval: 10s

sensor:
  - platform: dsmr
....
```
